### ISSUE TITLE
What do I need to configure to use this plugin?

### ISSUE THREAD

**Issue by jch254** [dougmoscrop/serverless-plugin-custom-domain#5]
I am trying to use this plugin but I'm not sure how to configure it. I understand that R53 records and ACM certs needs to be created elsewhere, is there a way to pass the ARNs etc. to this plugin? Thanks for any help

**Comment by dougmoscrop** [comment]
This plugin only needs to know the actual domain name you created.

Steps unrelated to this plugin:

- Use ACM to create a certificate for `*.myapp.com`
- Create an API Gateway Custom Domain called `api.myapp.com` choosing that certificate, this is technically a CloudFront Distribution.
- Go in to your Route53 Hosted Zone and add A/AAAA ALIAS records pointing to the distribution domain name - which will be something like `abcdef123456789.cloudfront.net`.

At this point you have DNS resolving to the Custom Domain (CloudFront Distribution) and it's going to respond over HTTPS with a certificate that is valid for the DNS address, but it has nothing to "back" the API requests. This plugin configures that - the [usage section](https://github.com/dougmoscrop/serverless-plugin-custom-domain#usage) is a couple lines of YAML, in this case you would set custom.domain to `api.myapp.com`

```yml
custom:
  domain: 'api.myapp.com'
```

**Comment by jch254** [comment]
Thanks @dougmoscrop you are a champion!

**Comment by prestontighe** [comment]
@dougmoscrop Why don't you put this in the readme?
